version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: hires
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: hires_db

  hires:
    image: 311141541828.dkr.ecr.us-east-1.amazonaws.com/hires:${IMAGE_TAG}
    env_file:
      - .env

  react-production:
    image: 311141541828.dkr.ecr.us-east-1.amazonaws.com/hires-react:${IMAGE_TAG}

  nginx:
    image: 311141541828.dkr.ecr.us-east-1.amazonaws.com/hires-nginx:${IMAGE_TAG}
    ports:
      - "80:80"
