services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: hires
      POSTGRES_PASSWORD: shubham@123
      POSTGRES_DB: hires_db
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "hires"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  hires:
    image: 311141541828.dkr.ecr.us-east-1.amazonaws.com/hires:${IMAGE_TAG}  # Use dynamic tag
    env_file:
      - .env
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M

  react-production:
    image: 311141541828.dkr.ecr.us-east-1.amazonaws.com/hires-react:${IMAGE_TAG}  # Use dynamic tag
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M

  nginx:
    image: 311141541828.dkr.ecr.us-east-1.amazonaws.com/hires-nginx:${IMAGE_TAG}  # Use dynamic tag
    ports:
      - "80:80"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
