services:
  db:
    image: postgres:latest
    container_name: Hires_db
    environment:
      POSTGRES_USER: hires
      POSTGRES_PASSWORD: shubham@123
      POSTGRES_DB: hires_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "hires"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    deploy:
      resources:
        limits:
          memory: 256M

  hires:
    image: 311141541828.dkr.ecr.us-east-1.amazonaws.com/hires:latest
    container_name: Hires_Django
    env_file:
      - .env
    volumes:
      - static_volume:/hires/static
      - media_volume:/hires/media
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M

  react-production:
    image: 311141541828.dkr.ecr.us-east-1.amazonaws.com/hires-react:latest
    container_name: Hires_react
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M

  nginx:
    image: 311141541828.dkr.ecr.us-east-1.amazonaws.com/hires-nginx:latest
    container_name: Hires_nginx
    volumes:
      - static_volume:/hires/static
      - media_volume:/hires/media
    ports:
      - "80:80"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M

volumes:
  postgres_data:
  static_volume:
  media_volume:
