# Generated by Django 5.1 on 2024-09-27 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseAPI', '0007_alter_joblevelmodel_job_level_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblevelmodel',
            name='job_level_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 10, 23, 54, 475785)),
        ),
        migrations.AlterField(
            model_name='jobpositionmodel',
            name='job_position_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 10, 23, 54, 475167)),
        ),
        migrations.AlterField(
            model_name='sectormodel',
            name='sector_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 10, 23, 54, 474469)),
        ),
    ]
