# Generated by Django 5.1 on 2024-09-27 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseAPI', '0016_alter_joblevelmodel_job_level_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblevelmodel',
            name='job_level_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 12, 13, 0, 378606)),
        ),
        migrations.AlterField(
            model_name='jobpositionmodel',
            name='job_position_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 12, 13, 0, 377460)),
        ),
        migrations.AlterField(
            model_name='sectormodel',
            name='sector_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 12, 13, 0, 376273)),
        ),
    ]
