# Generated by Django 5.1 on 2024-09-27 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterAPI', '0020_alter_jobdescriptionmodel_job_description_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescriptionmodel',
            name='job_description_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 13, 23, 26, 683667)),
        ),
        migrations.AlterField(
            model_name='recruiterbulkresumeuploadmodel',
            name='recruiter_bulk_resume_upload_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 13, 23, 26, 684981)),
        ),
        migrations.AlterField(
            model_name='recruiterresumecandidatemodel',
            name='recruiter_resume_candidate_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 13, 23, 26, 686720)),
        ),
    ]
